Application:
  name: ds_demo
  # make sure to use app security id assigned by registration
  security_id: -1

  Services:
   -
      type: Thrift
      language: Java
      service_name: ezelastic
      resources:
        cpu: small
        mem: small
        disk: small
      scaling:
          number_of_instances: 1
      artifact_info:
        bin: ezelastic.jar
        config: []
      database: ElasticSearch
